### ISSUE TITLE
Rename files to reflect chapter 2 split?

### ISSUE THREAD

**Issue by dpritchLibre** [BarkleyBG/LCC#102]
Hey @BarkleyBG, do you think it would be a good idea to rename the chapter files to reflect the fact that we have split chapter 2 into two chapters?  So in other words, to rename the files that are currently called `2a_blah_blah` and `2b_blah_blah` as chapters 2 and 3, and then shift the chapter number for the remaining filenames up one?

Doing so might save us some confusion / annoyance down the road.  I feel like now would be the perfect time to do it, since there are no outstanding PRs.  On the other hand, another reasonable approach would be to wait until a later stage when things are a little more cemented (since other chapters may move around yet), and then do all such changes at once.  What are your thoughts?

**Comment by BarkleyBG** [comment]
Seems like a good idea.
- Shall we save a space for SLURM chapter?
- This is also your chance to restructure the Tips/Courtesies/etc chapters in the way you see fit. Perhaps we should think hard on what we want to cover, and split it up by those topics?

Also, now that longleaf is merged in, I was thinking we should bump version to 0.5. Perhaps we should make these new chapters and THEN bump version?

**Comment by dpritchLibre** [comment]
Hmm, good questions.  I'm not totally sure yet about how to restructure things moving forward.  The courtesies chapter could certainly be merged into another chapter - probably Chapter 5 (running R jobs on \bcc/)?

I could see a reasonable structure as being something like:
*  **Chapter 5:** running an interactive or single batch job (merge courtesies chapter in here)
*  **Chapter 6:** running multiple jobs simultaneously, such as through arrays or for loops, etc (current chapter 8).  Maybe include a more in-depth treatment of Slurm commands here, since this chapter would be fairly short otherwise?
*  **Chapter 7:** Other common issues related to working on the cluster: installing programs, installing R packages, plotting in R, issues using the compiler, etc (current chapter 7).
*  **Chapter 8:** Longleaf

I guess I'm not yet sure where a good place for a detailed treatment of Slurm commands should go.  Does it warrant its own chapter?  Or is it more natural to include it organically with other related topics?  If it had its own chapter then maybe it would go better after chapter 5 or after chapter 6?  I think it may be hard to decide until we write further.

What do you think about this structure?  Maybe wait to decide what to do about Slurm topics until we're further along?

**Comment by dpritchLibre** [comment]
As for bumping the doc version due to additions to Longleaf chapter, those additions (at least the ones that I wrote) were quite small so I don't think it would be totally necessary.  Definitely though if we make some changes to the filenames / organization of the doc.

**Comment by BarkleyBG** [comment]
Should we close this issue now, or after we restructure as in #109 ?

**Comment by dpritchLibre** [comment]
Yes, I think we can close this now since it is effectively superseded by #109.
