### ISSUE TITLE
Create a verbatim-like LaTeX macro to bold terminal continuation lines

### ISSUE THREAD

**Issue by dpritchLibre** [BarkleyBG/LCC#104]
One of the open issues that we have right now is how to bold continuation lines in `lstlisting` terminal sessions.  For the prompt we just bold everything to the right of `userid@`, `localid@` or `onyenid@`, but for continuation lines we can't just bold everything to the right of `>` since that character may appear in text that we don't wan't to be bolded.  So I think that we have to manually bold continuation lines.

To aid this, I've been trying to create a macro, but I can't quite get one working.  I've enlisted help at https://tex.stackexchange.com/q/418273 - @BarkleyBG can you give me an upvote there to try and get some interest in the question?

**Comment by dpritchLibre** [comment]
There was a satisfactory answer to the above.  However I think there might be a better way.  Instead of turning the continuation line bold, maybe instead we can just escape the `>` characters that show up.  This is what is done in #105

**Comment by BarkleyBG** [comment]
- Can you add the special character to CONTRIBUTING so it's easier to recall this information?
     - Or should we create a `special_characters.md` file and put all of our handy macros in there for reference?

- How to deal with the continuation `+` in R?
