### ISSUE TITLE
Restructure chapters again

### ISSUE THREAD

**Issue by BarkleyBG** [BarkleyBG/LCC#109]
Restructure to chapters 0 through 10

**Comment by dpritchLibre** [comment]
*  .0. Intro
*  .1. Unix + Linux overview
*  .2. Shell commands
*  .3. Shell programming
*  .4. Cluster networking
*  .5. BIOS cluster fundamentals
*  .6. Running statistical software on the cluster (4 quandrants)
*  .7.  In-depth tour of SLURM commands
*  .8.  Scaling up: multiple jobs on the cluster
*  .9.  Additional cluster computing topics
*  .10. Longleaf
