### ISSUE TITLE
Citing same reference in two chapters

### ISSUE THREAD

**Issue by BarkleyBG** [BarkleyBG/LCC#113]
I want to cite Hadley's Advanced R in two different chapters. So, I put it in the .bib file for each of those chapters. But this means either 

1. use different bibid's and have the reference listed twice in the global bib
2. use the same bibid and deal with the fact that the global bib will have a duplicate

Currently the duplicated entry in the global bib spits out this warning:
```
Biber warning: [391] Utils.pm:169> WARN - 
Duplicate entry key: 'hadley-advancedr-global' 
in file 'references/global_refs.bib', 
skipping ...
```

Is there an easy way to tell biber to skip duplicates without this verbose warning? Or should we keep the verbose warning? Not sure how you want to continue - I'm pretty flexible here.

**Comment by dpritchLibre** [comment]
Haha, we talked about this issue potentially happening while over at your house one time, and now that time has come.  The answer is to just tell `create_global_refs.sh` to not create the entry twice.  I can take a look at it when I get a couple of free minutes.
