### ISSUE TITLE
Change chapter labels and refs from sec prefix to chap prefix

### ISSUE THREAD

**Issue by dpritchLibre** [BarkleyBG/LCC#120]
Opened as a response to a comment #117.  Here is a script to get you started.  For example if this script was called `change_sec_to_chap.sh` then you can change the prefixes for the label `sec:running_r_scripts` with the command

    ./change_sec_to_chap.sh running_r_scripts *.tex

Here is the script:

    #!/bin/bash
    
    usage='change_sec_to_chap.sh labelname filenames...'
    if (( $# < 2 )); then
        echo "$usage"
    fi
    
    # the first arg is the label name, remaining are filenames
    label_nm=$1
    shift
    
    # get temp filename for storage of sed output
    temp_nm=$(mktemp)
    
    # each iteration invokes `sed` for the current filename in order to change
    # references prefix from `sec` to `chap`.  If the call is successful then the
    # original filename is replaced by the output of `sed`.
    for file_nm; do
    
        # replace references prefix from `sec` to `chap`
        sed -e "s/{sec:$label_nm}/{chap:$label_nm}/" "$file_nm" > "$temp_nm"
    
        # if call to `sed` was a success then overwrite original file, otherwise
        # exit
        if (( $? == 0 )); then
    	mv "$temp_nm" "$file_nm"
        else
    	exit 1
        fi
    
    done

**Comment by BarkleyBG** [comment]
Good stuff. I would have just hacked it together myself. I have a couple questions, if you have the time.

- I understand that `shift` is a way of looking at the argument `$2` through `$N` (http://www.tldp.org/LDP/Bash-Beginners-Guide/html/sect_09_07.html)
- But I don't understand why those variables are callable via the variable name `file_nm`. I don't see where that was ever specified to be the appropriate variable name.

**Comment by dpritchLibre** [comment]
Excellent question.  That form is just syntactic sugar for stepping through all of the positional parameters.  To see the docs for this: https://www.gnu.org/software/bash/manual/html_node/Looping-Constructs.html

**Comment by dpritchLibre** [comment]
Exactly!

**Comment by BarkleyBG** [comment]
Awesome, thanks for the explanation. Good stuff.
