### ISSUE TITLE
Label sections in develop branch now?

### ISSUE THREAD

**Issue by BarkleyBG** [BarkleyBG/LCC#15]
Label Sections now or later? 

I'm building chapter 4 but I want to reference chapter 3 sections which are currently unlabeled and will be built separately.  Should we try to label everything now even though sections will change, or just save all referencing of labels until merge time?

**Comment by dpritchLibre** [comment]
I've come across the same issue.  So far I've been writing things like "in a later section" instead of "in Section \ref{sec:coolsec}" with the intention of replacing these later.

**Comment by BarkleyBG** [comment]
Shall I just label all sections and subsections in the develop branch? Then we could fetch, merge, update all other branches with these new labels, which may be close enough to the final product so as to not cause too many headaches. Plus, not many topic branches right now so maintenance would be small.

**Comment by BarkleyBG** [comment]
Closing because it was time-sensitive and now stale
