### ISSUE TITLE
Add grep and negative matching?

### ISSUE THREAD

**Issue by BarkleyBG** [BarkleyBG/LCC#29]
I think we should introduce `grep` and `grep -v` (negative matching) in 2.8: Navigating the Filesystem. Or in a similar section. I will make use of `grep` in the later sections, so in the interest of completion we should probable mention it earlier.

@dpritchLibre I'm handing this to you

**Comment by dpritchLibre** [comment]
Sure, we can add.  Actually, when I was making a list of the minimal set of POSIX commands needed for BIOS students, `grep` was the first command off the list.  I would think that it should go in _Section 2.9: Viewing the Contents of Files_, though.

**Comment by BarkleyBG** [comment]
Sounds good!

 - Brian

Sent from my phone; please excuse any typos


On Jul 10, 2017, at 9:25 AM, dpritchLibre <notifications@github.com<mailto:notifications@github.com>> wrote:


Sure, we can add. Actually, when I was making a list of the minimal set of POSIX commands needed for BIOS students, grep was the first command off the list. I would think that it should go in Section 2.9: Viewing the Contents of Files, though.

**Comment by dpritchLibre** [comment]
@BarkleyBG can you close this since I have consolidated with other additions to issue #42?  Thx
