### ISSUE TITLE
Add header to listings environment with script name

### ISSUE THREAD

**Issue by BarkleyBG** [BarkleyBG/LCC#31]
I'd like to refer to an instance of a listings environment as "my_r_script.R", and so it would be nice to have a header where the environment is clearly labeled as that file name. 

This link may be helpful:
https://tex.stackexchange.com/questions/85650/creating-a-custom-environment

**Comment by BarkleyBG** [comment]
This may be potentially helpful if we decide to make actual files and then simply input them into the tex code:
https://www.latex-tutorial.com/tutorials/advanced/latex-listings/

Another thought: I think I've seen an R package that can display output in a "nice" way that reduces the amount of copy-paste necessary. I'll keep an eye out for it.

**Comment by BarkleyBG** [comment]
Also adding the following link in case it's helpful for enumerating lines in listings environment
https://stackoverflow.com/questions/2178301/linenumbering-with-listings-package-in-latex

**Comment by dpritchLibre** [comment]
I used the `title=` option for listings a few times to do something like what you're referring to here.  It's not the fanciest thing in history, but I think I'm satisfied with it.  Is this enough for what you want to do?  For example on line 2143 of `2_shell_intro.tex` on the `cli_additions` branch, I use

    \begin{lstlisting}[style=bash-script, title=\code{run_multiple_sims.sh}]

See Section 2.14.1 of the pdf for how the output looks.  You can also add a label to the listing using the `label=` option for within-document hyperlinks.  See section 5.7 of the `listings` documentation for more details.

If you are indeed satisfied with this option then perhaps we can close the issue?

**Comment by BarkleyBG** [comment]
Do you like how the title looks? If so, I'll be happy to take it for now. (I'm also too lazy to pull and compile right now)

Also, I found the R package `reprex` for making reproducible examples easier:
https://github.com/tidyverse/reprex

**Comment by dpritchLibre** [comment]
I'm happy with it, at least until we find something that we like even better.
