### ISSUE TITLE
Milestones!

### ISSUE THREAD

**Issue by BarkleyBG** [BarkleyBG/LCC#33]
Hey @dpritchLibre , I think I'm gonna start using [Milestones](https://guides.github.com/features/issues) to group and keep track of the issues. What do you think?

For example, we could consider using the milestones
- Alpha version 
    - this would have most/all of the important information for a UNC BIOS reader. It wouldn't necessarily be _well_ written, but it would still be a standalone document that would help and add value
- Beta version 
  - This would be an updated version of Alpha, with better writing and more fully-fleshed out ideas
- Longleaf 
  - It would be great to teach longleaf too, but there's a couple major differences between UNC BIOS and longleaf that make me want to concentrate on them separately. Some things that act differently:
    - SLURM has different defaults
    - working with modules
    - two-tiered storage (long-term and scratch space)
  - Again, I want to write about this, but this is less important than Alpha and Beta, so I think it should get its own milestone to filter its corresponding set of issues.

Also, relatedly, I am excited for the power to use [custom issue labels](https://developer.github.com/v3/issues/labels/#create-a-label), aren't you?!?

**Comment by dpritchLibre** [comment]
Yes I'm also super-duper excited about milestones.  That all sounds good.

**Comment by BarkleyBG** [comment]
Custom labels are easily created via the following URL: https://github.com/BarkleyBG/LCC/labels or by clicking on the Labels button next to the search bar in the [issues page](https://github.com/BarkleyBG/LCC/issues).

I've deleted the `invalid` label and created a new labels for `clarify` (i.e. when something needs more writing to explain what's already written) and `generalize` (i.e. for adding a more general use when the writing explains only a specific use case)

[(as seen on SO)](https://stackoverflow.com/questions/29218900/how-to-create-custom-labels-for-issues-on-github`)

**Comment by BarkleyBG** [comment]
All remaining issues now have a milestone! Closing. 
💥 BOOM. 💥
