### ISSUE TITLE
Chapter 2 (CLI) additions

### ISSUE THREAD

**Issue by dpritchLibre** [BarkleyBG/LCC#42]
Opening this issue so as to consolidate additions for chapter 2 and provide a list that we can add to if we think of more things.  Am going to close two issues since they are rolled into this one: `sftp` (#30), and `grep` (#29).

- [x] Add `sftp` (see #30)
- [x] Add `grep` (see #29)
- [x] Add `find`
- [ ] Add `wget`?
- [ ] Add `tree`?
- [ ] Mention `cd -` option
- [x] Possibly move shell scripting introduction to this chapter?  This seems to make more sense here than introducing it when discussing Slurm.

**Comment by BarkleyBG** [comment]
Should we file this into the alpha or beta milestone?

**Comment by dpritchLibre** [comment]
I guess alpha?  I'll probably do these soon either before or while I do revisions on the chapter.

**Comment by BarkleyBG** [comment]
Alpha it is. I'll also send you more for edits/comments offline, perhaps by Monday.

Note that I added a single commit w/r/t #37. I may add another commit or two to Develop over the weekend, but they shouldn't be breaking, so you should be able to fetch and merge cleanly.

**Comment by BarkleyBG** [comment]
- [ ] Describe how to rsync when a pathname has spaces (i.e. windows users like yours truly)

https://askubuntu.com/questions/597605/rsync-over-ssh-path-with-spaces-does-not-work-with-quotes

**Comment by dpritchLibre** [comment]
@BarkleyBG I'm moving to close this, if you agree.  I think for the time-being I'll leave out `wget` and `tree`, and I'll just add a mention for `cd -` during the revisions.

Similarly, I haven't gotten to the issue for `rsync` with special characters in the filename, however, I'll do this during revisions also.

**Comment by BarkleyBG** [comment]
I'm adding this for later versions:

- [ ] `touch` command. Currently referenced in the `rsync` section. It's not the most useful but it does pop up now and then, so perhaps we should address it?

**Comment by BarkleyBG** [comment]
Moving to beta milestone now. This seems pretty good for alpha milestone. Maybe we will reopen in a month or so.
