### ISSUE TITLE
Missing page numbering in develop branch

### ISSUE THREAD

**Issue by dpritchLibre** [BarkleyBG/LCC#43]
Page numbering in `develop` isn't working properly.  On some pages it's omitted, and on other pages it shows up.  I don't see any instructions related to page numbering.  Any ideas?

**Comment by BarkleyBG** [comment]
Yeah I had noticed that. I had tried to play around with it but couldn't quite figure it out. I think this fits under #38; should we consolidate it to the same issue?

**Comment by dpritchLibre** [comment]
Yes, lets consolidate.  I had thought maybe this was something that was introduced when we put together the proposal for the department without the page numbers, but it sounds like it's something else going on.
