### ISSUE TITLE
Add title page and contributor information

### ISSUE THREAD

**Issue by BarkleyBG** [BarkleyBG/LCC#5]
A title page, and a page providing authors/contributors is necessary

**Comment by BarkleyBG** [comment]
We should do this before moving much further, @dpritchlibre

**Comment by BarkleyBG** [comment]
In the title/introduction we can add a link to this GH repo for people to open issues and edits. If we have that, then a built PDF can reside in the on-campus filesystem and we don't have to worry about adding a pdf to the repo.

**Comment by dpritchLibre** [comment]
Good idea to add a link to the repo.  Let's continue the discussion about building the pdf in issue #18.

**Comment by dpritchLibre** [comment]
We should add a working title now that other people may be viewing / joining the project.  Let me brainstorm a few quick ideas:

  * UNC BIOS student cluster guide
  * UNC BIOS unofficial cluster guide
  * UNC BIOS cluster guide / Written by students for students
  * UNC student guide for the BIOS and Longleaf computing clusters
  * UNC unofficial guide for the BIOS and Longleaf computing cluster

etc (omit the Longleaf references if / until we actually get to it).  Just some thoughts to get the ball rolling, I'm sure you can do much better!

**Comment by BarkleyBG** [comment]
migrating to #22 and marking this as duplicate
