### ISSUE TITLE
Glossaries directives in CONTRIBUTING.md

### ISSUE THREAD

**Issue by dpritchLibre** [BarkleyBG/LCC#53]
@BarkleyBG When you compile the glossaries using the `makeglossaries` application is the command on your system

    makeglossaries cluster_guide.tex

as it says in the `CONTRIBUTING.md` file?  On my system the command is

    makeglossaries cluster_guide

If you let me know then I can edit or append the directions in the file, as appropriate.

**Comment by BarkleyBG** [comment]
You're probably correct to drop the `.tex`. I just use hotkey shortcuts, and this is my output:

`Process started: "C:/Program Files (x86)/MiKTeX 2.9/miktex/bin/makeglossaries.exe" "cluster_guide"`

Go ahead and change it if you'd like
