### ISSUE TITLE
Initial release branch

### ISSUE THREAD

**Issue by dpritchLibre** [BarkleyBG/LCC#57]
We should make an initial release branch, meaning a branch that has only the first three chapters in it.  That way we can make sure that we don't have any references to later chapters or any other surprises.  

In general, we should probably have a branch that has only the production chapters in it, and another branch that has the entire kitchen sink in it, and then we keep adding chapters to the production branch until it catches up to the kitchen sink branch.

**Comment by BarkleyBG** [comment]
It may be tricky to have one branch (kitchensink) that has references to and from all chapters while also having one branch (reduced) that has only the first chapters and removes those references. I can't explain very well right now, but i forsee merge conflicts, or accidentally merging over old materials. Maybe not. I'll have to experiment.

This is my first thought, but I dont think it'll work:
1. Split  `reduced` from `develop`/`kitchensink`
2. Reduce `reduced` to just the first chapters, removing extra refernces to later materials
3. update `kitchensink` as desired
4. pull updates from `kitchensink` to `reduced`? but this will cause issues...


Perhaps the best thing is to remove references from the first chapters to later chapters in all versions, and then follow the above steps. It would be (slightly) irritating to work on `kitchensink` without all the references, but perhaps it's easiest?

**Comment by BarkleyBG** [comment]
What about:

1. branch off the initial release branch (called `init` or `reduced`)
1. Comment out the `\input{}` calls to the later chapters from the `cluster_guide.tex` main file in the `init` branch
    - Later chapters will not be compiled into the `init`ial release pdf
    - References from chapter 1 to chapter X_later will be compiles as `REF` errors
      - I think this would be fine, actually.
    - the .tex files for these later chapters will persist in the branch.
1. All of our work to develop the document will be done on the `develop`/`kitchensink` branch, which contains all sections and the full PDF
    - We can edit Chapter 1 in `kitchensink` and then merge it in to `init`. 
    - We can edit Chapter X_later in `kitchensink` and then merge it into `init`
    - Since the .tex files for Chapter 1 and Chapter X_later exist in `init`, these should merge cleanly.
       - I think that since the `\input{}` calls is commented out in `init`, we won't have to worry about changes to later chapters

Seem reasonable? If so, I can try it.

**Comment by BarkleyBG** [comment]
I need to make reference to two diagrams that I find really helpful:

This beautiful branch diagram: 
nvie.com/posts/a-successful-git-branching-model/

This beautiful ohshoot flowchart:
http://justinhileman.info/article/git-pretty/

- So, perhaps we call the "initial release branch" `release`?
   - `master` would be a stable release
   - `release` would be ahead of master (i.e., when `master` is tagged with `v0.3` then `release` could be working on version 0.3+
- Shall we continue to do all work in `develop` (the kitchen sink)?

**Comment by dpritchLibre** [comment]
Brilliant!  What a luxury to have a git whiz on the team!  Agree 100% with everything you've proposed.

One small confusion I have.  When we merge `develop` into `release` won't the commented out `\input` statements in `cluster_guide.tex` be uncommented?

However, I think I may have found an answer to this problem in this [amazingly slick post](https://medium.com/@porteneuve/how-to-make-git-preserve-specific-files-while-merging-18c92343826b).  What this would do is cause a specified file to always keep the original version when merging a branch.  So we would apply this to `cluster_guide.tex`, and it will stay local to each branch!

Of course, this has the downside that there will be times that we actually do want changes to other parts of `cluster_guide.tex` to be reflected across branches.  So what I propose to do to sidestep this issue is to except just the 8 chapter `\input` statements or so into a new file called `body.tex` or something similar, and just `\input` that file from `cluster_guide.tex`.  Then `body.tex` will be the fill that we instruct git to leave alone when performing merges.

Am I thinking about this all correctly?  If we're able to pull this off, I think we will have officially graduated from "git novices" to "knowing just enough git to shoot ourselves in the foot" status!

**Comment by BarkleyBG** [comment]
> One small confusion I have. When we merge `develop` into `release` won't the commented out `\input` statements in `cluster_guide.tex` be uncommented?

#### Short: 
I dont think so.
#### Long:
1. `develop` is currently at commit C1. Start the `release` branch there, too.
2. In `release`, comment out the `\input{}` lines. Stage and commit. This is commit C2.
3. Checkout `develop`. Do work. Make a commit. This is C3. Lather, rinse, repeat (i.e., commits C3+)
4. Checkout `release`. Merge C3+ from `develop` into `release`. 
   - As long as C3+ have not changed the lines surrounding the  `\input{}` lines, this should merge cleanly.
   - Since C3+ haven't made any changes to the  `\input{}` lines, git will not make any changes to the  `\input{}` lines. 
      - i.e., the commented-out  `\input{}` lines in `release` will stay commented out.

I think this would work! Or, I could be totally wrong about everything.

**Comment by BarkleyBG** [comment]
not related: I followed your link and I think we should read this to git good

https://medium.com/@porteneuve/getting-solid-at-git-rebase-vs-merge-4fa1a48c53aa

An argument for when to rebase instead of merge:
>The real question you should ask yourself is this: “what does this other branch represent?” 
>
>Is it just a local, temporary branch, that I had just created out of precaution, in order for master to remain clean in the meantime? If so, it is not only useless but downright counter-productive for this branch to remain visible in the history graph [via a merge], as an identifiable “railroad switch.”

**Comment by dpritchLibre** [comment]
Okay. I think I've convinced myself that the comments will stay.  Related: why am I so bad at git?  I think I have a fundamental brain block when it comes to this stuff.  It seems to come so intuitively to you.

So yeah, disregard my previous comment, and let's do it exactly how you suggested.

**Comment by BarkleyBG** [comment]
Dude, I had to take 4 long comments to figure this out. And we haven't even determined if it's gonna work! This is tough stuff!

I can attempt this daring maneuver in the next few days. Or would you want to do this live and in person on Friday?

**Comment by dpritchLibre** [comment]
Nah just go for it whenever time permits.  I have full faith that you'll pull it off.

**Comment by BarkleyBG** [comment]
Initial release branch is up!

a2c1f5551b64caa445b2d8baa9f661ad83432a2a is an example of our new workflow: Commits from develop will be merged into release.

Closing this! Yay!

**Comment by BarkleyBG** [comment]
@dpritchLibre Are we being silly by having a `release` branch? Isn't that what `master` is for? 

## for example
Let's say we're at version 3.1. 
- So `master` is at the commit tagged `v3.1`. 
- We start a milestone called `v3.2` with a list of things we want to implement
- The next commit (in `develop` or even a sub-branch) would change the `doc_ver=3.1.9000` in the .tex macro.
- Once `develop` ticks off everything in the `v3.2` milestone, then `doc_ver=3.2` and we bring `master` up to that (tagged) commit.

That seems more natural, right?

Adding to #86

**Comment by dpritchLibre** [comment]
So `develop` has all the chapters, but when we release something it won't have all of the chapters yet.  I think the point of the intermediary `release` branch was so that we could compile the document without the extra chapters and fix any broken links etc. caused by removing the chapters, without doing that in the `master` branch.

I don't think it's super necessary to have this intermediate stage so whatever you think is best is fine with me.

**Comment by BarkleyBG** [comment]
Ah! I'd forgotten that we aren't including all chatpers. good point. case closed!
