### ISSUE TITLE
Order of intro

### ISSUE THREAD

**Issue by BarkleyBG** [BarkleyBG/LCC#59]
My suggestion:
1. ToC
2. Preface
3. About this document
4. Acknowledgements
5. Glossary
6. Acronyms

Then, start the chapters.
Sound good @dpritchLibre?

**Comment by dpritchLibre** [comment]
I think that we already discussed this in person, but yes, sounds great

**Comment by BarkleyBG** [comment]
now that we've bumped to new biber stuff and version 0.3 this issue is ripe for fixin right?

**Comment by BarkleyBG** [comment]
@dpritchLibre Do you mind if I change up the order from the current to what I have suggested above?

**Comment by dpritchLibre** [comment]
Of course, yes have at 'er
