### ISSUE TITLE
Relabel chapters?

### ISSUE THREAD

**Issue by BarkleyBG** [BarkleyBG/LCC#64]
I'm having a hard time finding the `\ref{sec:this_chapter_title}` in TeX. Should we relabel the chapters?

E.g., for the chapters,

0. change `\label{sec:chapter_zero}` to `\label{chp:zero}` or something
1. change `\label{sec:linux-overview}` to `\label{chp:unix}`
2. change `\label{sec:shell-environment}` to `\label{chp:shell}`

Of course, then we would have to change all downstream references..... Thoughts?

**Comment by BarkleyBG** [comment]
@dpritchLibre let's decide this before we get any further

**Comment by dpritchLibre** [comment]
Yes, please feel free to change the labels if you wish.

However, I don't understand how finding the chapter reference labels is any difficulty?  It's literally just within the first few lines of each file.  So for example you can list them by

    head -n3 {0..8}*

or if you wanted to get a little fancier,

    head -n3 {0..8}* | sed -n 's/.*label{\([^}]*\)}.*/\1/p'

**Comment by dpritchLibre** [comment]
That reminds me: can I suggest that you use `hyperref`'s `\autoref` command in place of `\ref` when making references?  This command automatically adds the `Section`, `Chapter`, `Figure`, etc. prefix to your reference and most importantly enforces a consistent nomenclature across the document.  The definitions of these can be changed and are found on line 137-140 of `ii_preamble_settings.tex`.

**Comment by BarkleyBG** [comment]
Nice trick with the shell command. I'd never thought of that (perhaps because I usually don't have a shell open when writing)

And yes, I'd forgotten about `\autoref`. I was thinking about it just the other day, yet still forgotten!

Closing this.
