### ISSUE TITLE
Organize latex directory structure

### ISSUE THREAD

**Issue by dpritchLibre** [BarkleyBG/LCC#66]
I'm finding that the `latex` directory is becoming overly cluttered for my taste.  If you include all of the LaTeX build artifacts, I count about 40 files in the directory.  My suggestion is to create a few more subdirectories and move some of the files into them.  I'm thinking that we could add the following subdirectories:

1.  `preamble` (`i_preamble_defs.tex`, `ii_preamble_settings.tex`, etc)
2.  `frontmatter` (`acknowledgements.tex`, `contributer_information.tex`, etc)
3.  `chapters`

After this the only non-directory files remaining would be the `cluster_guide.*` files.
@BarkleyBG would you be opposed to me performing this reorganization in a PR?  Any changes or suggestions are welcome (in particular, is there a better name than `frontmatter`?).

**Comment by BarkleyBG** [comment]
I totally agree. I had been looking at something very similar. Go for it!


On Nov 18, 2017, at 6:25 PM, dpritchLibre <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm finding that the latex directory is becoming overly cluttered for my taste. If you include all of the LaTeX build artifacts, I count about 40 files in the directory. My suggestion is to create a few more subdirectories and move some of the files into them. I'm thinking that we could add the following subdirectories:

  1.  preamble (i_preamble_defs.tex, ii_preamble_settings.tex, etc)
  2.  frontmatter (acknowledgements.tex, contributer_information.tex, etc)
  3.  chapters

After this the only non-directory files remaining would be the cluster_guide.* files.
@BarkleyBG<https://github.com/barkleybg> would you be opposed to me performing this reorganization in a PR? Any changes or suggestions are welcome (in particular, is there a better name than frontmatter?).

**Comment by BarkleyBG** [comment]
I can't think of anything better than `frontmatter` at the moment. Do as you wish.

**Comment by BarkleyBG** [comment]
After you do this I'll take a stab at #59

**Comment by dpritchLibre** [comment]
Alright!  Decisions made, progress (hopefully) achieved!
