### ISSUE TITLE
Do glossary and acronyms provide sufficient indexing?

### ISSUE THREAD

**Issue by BarkleyBG** [BarkleyBG/LCC#69]
It seems the `\gls{}` command keeps track of where each word was used in the text (as an index would).

It also seems that the custom `\glindex{}` command makes for a weird indexing of topics, where the page number references in the glossary are replaced with references to only the index.

@dpritchLibre, I recommend you change all the `\gls{cli}` calls in chapter 2 to `\glindex{cli}` (on the `makeindex` branch), and then carry out the steps to re-compile (the index, the glossaries, and the tex) to see what it looks like.

Perhaps we are good for now without `\glindex{}`?

**Comment by dpritchLibre** [comment]
Ho Lee Fuk - I am not a smart man (I hope you get the reference to the [plane crash practical joke](https://www.huffingtonpost.com/2013/07/12/asiana-pilots-fake-names-racist_n_3588569.html)).  Here the whole time I was thinking that the term that's put in the index was the one from the text.  So for example, your source might say

    here is some \index{text} and so on

and I had thought the output would be `here is some text and so on` with `text` added to the index, but in fact, the output would be `here is some and so on`.  So in other words the text should contain source code of the form `The reason that we discuss the \gls{cli}\index{CLI}`.

Thus your original suggestion for `glindex` from way back when is the right one, i.e.

    \newcommand{\glindex}[1]{\gls{#1}\index{#1}}

I guess you would just have to change the places in the glossaries definitions files to match the text that we want to show up in the index, so for example `\newacronym{cli}{CLI}{Command Line Interface}` would have to be `\newacronym{CLI}{CLI}{Command Line Interface}`.

On the other hand, in the interest of consistency maybe it would be better to explicitly write out the `\index` command after the word anyway.

Anyway, my apologies for unnecessarily creating this confusion.

**Comment by BarkleyBG** [comment]
shall i try to reimplment the `\glindex{}` command

**Comment by BarkleyBG** [comment]
I can't remember if I've mentioned this before, but I pushed a `makeindex` branch that has the most recent copy of stuff related to `\glindex{}`
