### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by dpritchLibre** [BarkleyBG/LCC#7]
We should add a license to the repo.  For example, the GPL-3 can be found at:  https://www.gnu.org/licenses/gpl-3.0.txt

**Comment by BarkleyBG** [comment]
Oh, wow, I thought I had.

Why don't you choose one that suits your fancy and put it in a PR? GPL-3 seems reasonable for now.

**Comment by dpritchLibre** [comment]
Added as part of PR #12

**Comment by BarkleyBG** [comment]
Will be merged into develop as part of #12 in initial_scope branch
