### ISSUE TITLE
Happy git (and a happy shell)

### ISSUE THREAD

**Issue by BarkleyBG** [BarkleyBG/LCC#84]
I found this resource to be excellent for getting a good shell as a windows user:
http://happygitwithr.com/install-git.html 

> Option 1 (highly recommended): Install Git for Windows, also known as msysgit or “Git Bash”, to get Git in addition to some other useful tools, such as the Bash shell. Yes, all those names are totally confusing, but you might encounter them elsewhere and I want you to be well-informed.
>
> We like this because Git for Windows leaves the Git executable in a conventional location, which will help you and other programs, e.g. RStudio, find it and use it. This also supports a transition to more expert use, because the “Git Bash” shell will be useful as you venture outside of R/RStudio.

And this last part helped me get git bash through the RStudio terminal:

> NOTE: Select “Use Git from the Windows Command Prompt” during installation

I also totally agree with Jenny's argument for SourceTree (and I don't know if you've committed [LOL] to magit, or if youd be interested in GitKraken) 

http://happygitwithr.com/git-client.html#git-client

Thanks to the Rstats world for this resource!

So this should be added to chapter 0 / setup, really.

**Comment by dpritchLibre** [comment]
I view this as being two separate issues:
1.  Installing Bash
2.  Accessing a Bash terminal through RStudio

For (1), In chapter 2 (CLI) there is a section about installing a shell on Windows.  Why don't you add a section about this installation option there?

For (2), I have in mind a section where we talk about accessing a remote R session in RStudio and Emacs.  Maybe we could put (2) in the same chapter with these topics?

**Comment by BarkleyBG** [comment]
1. Yeah I think this resource will be invaluable for teaching Windows users how to install some kind of shell. It'll be great.
2. I think the added utility of using Emacs or RStudio for remote work is excellent, so I would certainly want to play this up when it comes time to talk about ssh'ing to a remote machine.

So:
- [ ] Add "install git bash" to chapter 0 (or perhaps in an appendix that chp0 refers to)
- [ ] Note that Emacs and RStudio each offer both an R IDE and a terminal
- [ ] Note that Emacs and RStudio each provide a hotkey to send keystrokes from the IDE to the terminal (and a remote machine)

**Comment by dpritchLibre** [comment]
Why don't you add the git + MSYS installation to chapter 2 (rather than an appendix) and link to it from chapter 0?  You can add the website to the chapter bibliography too now that an awesome bibliography framework is in place :)

**Comment by BarkleyBG** [comment]
That's a consideration. We may do that.

I see "installation and setup" as a hugely important part, but also very separate from our other goals (of instruction, introducing tools, etc). In a way, I like how chapter 2 is about "open your shell and learn these programs". I like how the pains of installing a shell (for windows users) are separated from its usefulness.

Let's get draft 1 done, and then in draft 2 we can get feedback to see what people wanted to know where. Feedback has already told us a lot we didnt expect!

**Comment by dpritchLibre** [comment]
Hmm, I think I see your point that maybe we should separate "using the shell" from "installing / accessing the shell."  I think I'd probably be okay moving the "installing / accessing the shell" section that currently exists in chapter 2 to an appendix if you would prefer.  Just as long as we keep all of the installation stuff together.

**Comment by BarkleyBG** [comment]
We can leave it for now. 

Perhaps outside of Chapter 0 we could put all installation stuff in appendix? I don't know, I'll have to catch up on where we're at.

**Comment by dpritchLibre** [comment]
I'm open to that idea - lets put it on the agenda for discussion Monday.

**Comment by BarkleyBG** [comment]
Related, perhaps:
http://www.msys2.org/

**Comment by BarkleyBG** [comment]
Closed in #116
