### ISSUE TITLE
Chapter 0 improvements

### ISSUE THREAD

**Issue by BarkleyBG** [BarkleyBG/LCC#90]
This are migrated from #62 , which was accidentally closed via commit.

- [ ] Screenshots for MacOS logon
- [ ] Edit the Ubuntu/linuxOS logon
- [x] Add something on batch jobs?
- [ ] Clean up the "Review and look ahead" section

Also, from #86:
- [x] Rephrase some of the VPN language
    - [x] reference chapter 3 when possible
    - [x] Acknowledge heuristic nature of some of the writing about VPN in chapter 0

EDIT:: these need to be migrated to a separate issue, later (see below for Dave's comment)

- [x] Add the bash installation via Happy Git #84 
    - [x] Add a walkthrough for initial SSH login to the cluster via RStudio 
    - [x] Add the #84 and more 'recomneded terminals' to Appendix (from #86)

**Comment by dpritchLibre** [comment]
I thought we had agreed to add the MSYS installation via [git for Windows](http://gitforwindows.org) with the instructions for other shell installation options for Windows?

**Comment by BarkleyBG** [comment]
We may have agreed on that; i can't exactly remember. I simply copied and pasted the checkboxes here, so I may have lost something in translation.

Are you suggesting we move the following out of chapter 0 and into chapter 2 and/or the appendix?
- Add the bash installation via Happy Git #84
    - Add a walkthrough for initial SSH login to the cluster via RStudio
    - Add the #84 and more 'recomneded terminals' to Appendix (from #86)

We can do that. It's easier on me in the short-term if I don't have to write about this stuff in chapter 0, anyways!

**Comment by dpritchLibre** [comment]
Right on right on.  In short, to what you wrote above: yes, that's what I'm suggesting, with the exception of logging into the cluster from RStudio.

My feeling is that we should keep all of the installation options for Unix-like shells on a Windows system in the same place, wherever that may be.  Right now they live in chapter 2, but I am open to moving the section elsewhere if there is a better fit for it, such as chapter 0 or the appendix.

I also view the installation of a Unix-like shell as being in a different section then "Accesing a Unix-like shell from editor" (i.e. RStudio, Emacs, etc.).

So my suggestion would be to say something like this in chapter 0:

    While the SSH Communications Security SSH shell is a good first option to get started 
    interacting with the BIOS cluster on a Windows machine, there are alternative approaches 
    for interacting with the cluster that are more flexible and provide more capabilities than a
    standalone SSH client such this.  In Section blah-blah-blah we discuss the merits of these
    alternatives and provide information on how to install them on your system.  The reason
    that we present the SSH Communications Security SSH shell first is that it is probably the
    easiest to install, and it is in some sense the "official" campus SSH client since it is 
    provided by UNC Software Acquisition, and there is lots of documentation and support 
    available for it through UNC.  A second good reason for installing the SSH 
    Communications Security SSH shell is that is comes with a very capable GUI file transfer 
    client that readers may find valuable for moving their files to and from the BIOS 
    filesystem.  We discuss the use of the GUI file transfer client in Section blah-blah-blah.

**Comment by BarkleyBG** [comment]
got it. I added that to chapter zero. Thanks; that was helpful.

**Comment by BarkleyBG** [comment]
### About batch jobs in chapter 0

I think this will just be a short section detailing _what_ a batch job is, but not describing _how_ to run one. For example, this would describe:
- interactive jobs are a two-way street with constant commuication. Batch jobs are a two way street where the parties take turns
- We could mention that there's a lot of other topics involved (slurm, shell, etc) in order to run a job
- we could mention the benefits of batch jobs

#### seeding a first batch job?
THis may also be a good time to "seed" a batch job with an example Bash and R scripts saved in a common location. Can we make these files non-writeable, but copyable? If so, then we could instruct invidiuals to
1. find the files
2. copy them to their home directory
3. (will they have to enter their own email address?)
4. provide the command for running the file

**Comment by BarkleyBG** [comment]
Chapter 0 is looking better. There are still some outstanding checkboxes here, but we have more pressing topics, so closing for now
