### ISSUE TITLE
Chapter 2 considerations 

### ISSUE THREAD

**Issue by BarkleyBG** [BarkleyBG/LCC#92]
Some tasks for Chapter 2 from #86 . Perhaps relates to #83 ?

- [x] When discussing how to access a CLI on Windows:
    - keep it short 
    - Refer to other sections for more details
    - However, important information must not be stashed in the appendix
    - We will (later) add info on on how to install/use RStudio + Emacs (rather than SSH GUI) for unix-ecosystem commands to appendix 
         - (This is a pretty broad/vague bullet point. We should migrate it to an GH Issue when we're serious about this.)

- [x] Let's pre-emptively add "Back to Chapter 0" etc at the end of Chap 2, etc. 
   - Link between them nicely since people will probably be jumping around

**Comment by dpritchLibre** [comment]
It occurred to me that rather linking "back to chapter 0" at the end of chapters, should we link to the TOC since you can jump anywhere from there?

**Comment by BarkleyBG** [comment]
Ok, great idea.  Here's how to implement it: https://tex.stackexchange.com/questions/164285/clickable-link-back-to-the-table-of-contents

Should we put one at the end of each chapter, too? 
1. We could add it at the last line of every `chapter_0.tex` file
2. Or we could add it in the main `cluster_guide.tex` file as shown below:
   
     \input{chapter_0.tex}
     \hyperlink{toc}{Back to Table of Contents}.
    
     \input{chapter_1.tex}
     \hyperlink{toc}{Back to Table of Contents}.
     % etc

Which do you prefer? I'll add `hypertarget` to the develop branch so we can link back to the TOC. I could also add these links back to the TOC, either in 1. the individuals files, or 2. the `cluster_guide.tex` file. I think either 1. or 2. has the possibility of merge conflicts, but perhaps 2. is a little more idiot-proofed (because we're less likely to forget a `\hyperlink{toc}` call if they're all visible in the same file.

**Comment by dpritchLibre** [comment]
The above discussion is continued in #94.

**Comment by BarkleyBG** [comment]
I marked the 2nd checkbox as "done" because #94 is closed.

**Comment by dpritchLibre** [comment]
Can we close this issue now that the PR for chapter 2 (#83) is ready to be merged?
