### ISSUE TITLE
Links back to TOC?

### ISSUE THREAD

**Issue by BarkleyBG** [BarkleyBG/LCC#94]
Per the discussion in #92  (I'm migrating the discussion from there to here), it seems that we want to add a `\hypertarget{toc}` to the TOC so we can link back to it. 

Do we want to link back to the TOC at the end of every section? 

How:  https://tex.stackexchange.com/questions/164285/clickable-link-back-to-the-table-of-contents

Two options:
1. We could add it at the last line of every `chapter_*.tex` file
2. Or we could add it in the main `cluster_guide.tex` file as shown below:
```
    \input{chapter_0.tex}
    \hyperlink{toc}{Back to Table of Contents}.

    \input{chapter_1.tex}
    \hyperlink{toc}{Back to Table of Contents}.
    % etc
```
Which do you prefer @dpritchLibre ?

I think either 1. or 2. has the possibility of merge conflicts, but perhaps 2. is a little more idiot-proofed (because we're less likely to forget a `\hyperlink{toc}` call if they're all visible in the same file.

I want to add the `\hypertarget` to v0.4 before #73  is merged. And i'd also prefer to solve this issue (and close it with a PR to develop) before v0.4, just to have that done with.

**Comment by dpritchLibre** [comment]
Cool!  Nicely done.  I'm happy with either approach, so I would just say pick one and go for it!  

I have some boilerplate at the end of the chapters related to the bibliography, so you may have to put the hyperlink before the call to print the bibliography.  If you want to go with option 2, then you are welcome to pull those calls out of the chapters and into the top-level tex file.  Whatever works for you.
