### ISSUE TITLE
permission denied for makefile

### ISSUE THREAD

**Issue by BarkleyBG** [BarkleyBG/LCC#97]
I’m having some issues with the make command. Perhaps I've got a write-protected global bib file?

 ```
me@mine  stuff/LCC/latex (branch)
$ make
references/create_global_refs.sh -o references/global_refs.bib references/1_unix_and_linux.bib references/2_shell_intro.bib references/3_computing_clusters.bib references/4_running_r_scripts.bib references/6_tips.bib
make: execvp: references/create_global_refs.sh: Permission denied
make: *** [references/global_refs.bib] Error 127
```

Here's files in the `references` dir:
```
$ ls references/
1_unix_and_linux.bib  3_computing_clusters.bib  6_tips.bib              global_refs.bib
2_shell_intro.bib     4_running_r_scripts.bib   create_global_refs.sh*  tests/
```

long output:
```
$ ls -l references/
  total 56
-rw-r--r-- 1 me 197121 12771 Feb  1 12:26 1_unix_and_linux.bib
-rw-r--r-- 1 me 197121  6178 Dec  4 12:48 2_shell_intro.bib
-rw-r--r-- 1 me 197121  3651 Dec  4 12:48 3_computing_clusters.bib
-rw-r--r-- 1 me 197121  1029 Feb  1 12:26 4_running_r_scripts.bib
-rw-r--r-- 1 me 197121   805 Feb 20 13:12 6_tips.bib
-rwxr-xr-x 1 me 197121 11606 Feb  1 12:26 create_global_refs.sh*
-rw-r--r-- 1 me 197121  4634 Feb  1 12:26 global_refs.bib
drwxr-xr-x 1 me 197121     0 Dec  4 12:48 tests/
```

**Comment by dpritchLibre** [comment]
That's weird.. I would have thought that you have write execute for everything and execute privilege for the script.  Do you get an error if you run the following command from the `references` directory?

    ./create_global_refs.sh -s 2a_shell_intro.bib

Thanks.  As an aside, typing the following gives you the instructions on how `create_global_refs.sh` is supposed to work:

    ./create_global_refs.sh -h

**Comment by BarkleyBG** [comment]
Good stuff!! I just had some fun with testing this out. In short,

(brief question: Why do I need to precede the bash file with the `./` ? If I dont tell it that the bash file is in this directory, does it try to look in `PATH` or something? 

```
$ ./create_global_refs.sh -s 6_tips.bib ## works

$ ./create_global_refs.sh -s 6_tips.bib >> testbib.bib    ##works

$ ./create_global_refs.sh -o test2.bib testbib.bib   ##works

$ ./create_global_refs.sh -o test2.bib testbib.bib 2_shell_intro.bib  ##works

```

### Creating global refs by hand
and finally, this seems to work, too:

```
$ ./create_global_refs.sh -o global_refs.bib 1_unix_and_linux.bib 2_shell_intro.bib 3_computing_clusters.bib 4_running_r_scripts.bib 6_tips.bib
```

### makefile

So, after updating the `global_refs.bib` (as in Creating global refs by hand), I then tried the make file again:

```
$ cd ../ ## go to "latex" dir
$ make
```

I did not get the `Error 127` as shown above.

I did get some other funky output from the `make` command. I'll paste it below in "more errors". However, I usually/always get some funky output from `make` and the related `pdflatex`, etc, because, as you well know, my system setup is very weird. (For the sake of the longevity of this document, hopefully my setup is weirder than most).

#### upshot // presumed solution

The `cluster_guide.pdf` now seems to have all chapter- and global- bibliography references as desired. I When getting the `Error 127` Above, then follow these steps:

1. `cd` to references directory
```
$ cd references/
```
2. Create global bibliography "by hand" . the `create_global_refs.sh` function must/should be called with:
    - the `-o global_refs.bib` option to send output to the global referneces file (although I suppose this could be accomplished by piping)
    - All chapter bibliographies must be specified by name (use tab completion to save time!)
```
$./create_global_refs.sh -o global_refs.bib 1_unix_and_linux.bib 2_shell_intro.bib 3_computing_clusters.bib 4_running_r_scripts.bib 6_tips.bib <any other chapter bibfiles availale>
```
3. `cd` back to the latex directory (parent of references)
```
$ cd ../
```
4. call the make file again
```
$ make
```

#### more errors?
An excerpt of the output I see (note that the .pdf is compiled as desired, i think)
```
This is pdfTeX, Version 3.14159265-2.6-1.40.18 (MiKTeX 2.9.6500)
entering extended mode
This is makeindex, version 2.15 [MiKTeX 2.9.6500] (kpathsea + Thai support).
Scanning input file cluster_guide.idx....done (13 entries accepted, 0 rejected).
Sorting entries....done (50 comparisons).
Generating output file cluster_guide.ind....done (41 lines written, 0 warnings).
Output written in cluster_guide.ind.
Transcript written in cluster_guide.ilg.
Latexmk: Summary of warnings:
  Latex failed to resolve 10 reference(s)
Collected error summary (may duplicate other messages):
  pdflatex: Command for 'pdflatex' gave return code 1
      Refer to 'cluster_guide.log' for details
Latexmk: Use the -f option to force complete processing,
 unless error was exceeding maximum runs of latex/pdflatex.
make: *** [all] Error 12
```
And here's one of the weird errors that seems related to my system, and not the document:
```
Use of uninitialized value $separator in regexp compilation at C:\Users\my_user_name\AppData\Roaming\MiKTeX\2.9\scripts\latexmk\latexmk.pl line 8527.
```

**Comment by BarkleyBG** [comment]
I think how to proceed here:

1. I add my 'presumed solution' as an edit to the original comment.
2. We close this issue
3. if you have any concerns about the other bad output from `make`, then we can start a new issue

**Comment by dpritchLibre** [comment]
Wow, nice rundown, thanks!  You're getting good at this sort of thing.  

I wouldn't close this issue yet.  We don't want people to have to update the global refs manually every time that a change is made.

As for the leading `./`,  yes you're exactly correct.

----------------------------------

I'm glad to hear that `create_global_refs.sh` seems to be working on your system.  Can you try deleting `global_refs.bib`, and then run

    make references/global_refs.bib

Does that create a new version of `global_refs.bib`?  Note that it is important that you delete the file first.  Otherwise `make` sees that the updated version is already there and consequently does not try to recreate it, which is why you are able to run `make` successfully after you manually create the file.

---------------------------------

When you run `pdflatex` outside of `make`, do you get an error also?  Do you get one when you run it through the IDE?

**Comment by BarkleyBG** [comment]
I'll try `make references/global_refs.bib`.

I have files for `latex/cluster_guide.text.bbl` and `latex/cluster_guide.text.blg` now. They are not staged. Should I remove them, or add to `.gitginore`? Are they necessary for building the .pdf? If so, i think ignore, correct?

**Comment by dpritchLibre** [comment]
Hmm, I haven't seen those ones yet.  But yeah, I'd just go ahead and add to the `.gitignore` in case other people come across them at some point.

**Comment by BarkleyBG** [comment]
No dice! From `latex/` dir
```
$ rm global_refs.bib
$ make references/global_refs.bib
references/create_global_refs.sh -o references/global_refs.bib references/1_unix_and_linux.bib references/2_shell_intro.bib references/3_computing_clusters.bib references/4_running_r_scripts.bib references/6_tips.bib
make: execvp: references/create_global_refs.sh: Permission denied
make: *** [references/global_refs.bib] Error 127
```

**Comment by dpritchLibre** [comment]
Weird!!!  What does `ls -l` say for the `references` directory?  In other words, if you run `ls -l` in the `latex` directory, what does it say for the line corresponding to `references`?

**Comment by BarkleyBG** [comment]
from `latex`

```
$ ls -l 
drwxr-xr-x 1 me 197121       0 Feb 22 11:23 chapters/
...
-rw-r--r-- 1 me  197121    1607 Feb  1 12:26 Makefile
drwxr-xr-x 1 me 197121       0 Feb  9 11:00 preamble/
-rw-r--r-- 1 me  197121     967 Feb 20 13:32 q.log
drwxr-xr-x 1 me  197121       0 Feb 22 11:17 references/
drwxr-xr-x 1 me  197121       0 Feb  1 12:26 scripts/
```

**Comment by dpritchLibre** [comment]
I've created a PR in #99 that may or may not fix this.

**Comment by BarkleyBG** [comment]
Good news, this may have worked. I'm re-opening so we can be sure.

I pulled down the merge and tried again. It ran and produced a PDF that seems to look good. There is a lot of output from the `make` call, which I'll show here:

```
$ make
latexmk --pdf --silent cluster_guide
Use of uninitialized value $separator in regexp compilation at C:\Users\me\AppData\Roaming\MiKTeX\2.9\scripts\latexmk\latexmk.pl line 8527.
Use of uninitialized value $separator in regexp compilation at C:\Users\me\AppData\Roaming\MiKTeX\2.9\scripts\latexmk\latexmk.pl line 8528.
Use of uninitialized value $search_path_separator in concatenation (.) or string at C:\Users\me\AppData\Roaming\MiKTeX\2.9\scripts\latexmk\latexmk.pl line 1855.
Use of uninitialized value $print_cmd in string at C:\Users\me\AppData\Roaming\MiKTeX\2.9\scripts\latexmk\latexmk.pl line 2686.
Latexmk: Run number 1 of rule 'biber cluster_guide'
Latexmk: Run number 1 of rule 'pdflatex'
This is pdfTeX, Version 3.14159265-2.6-1.40.18 (MiKTeX 2.9.6500)
entering extended mode
This is makeindex, version 2.15 [MiKTeX 2.9.6500] (kpathsea + Thai support).
Scanning input file cluster_guide.idx....done (123 entries accepted, 0 rejected).
Sorting entries....done (955 comparisons).
Generating output file cluster_guide.ind....done (142 lines written, 0 warnings).
Output written in cluster_guide.ind.
Transcript written in cluster_guide.ilg.
Latexmk: Summary of warnings:
  Latex failed to resolve 61 reference(s)
  Latex failed to resolve 23 citation(s)
Latexmk: Run number 1 of rule 'cusdep glo gls cluster_guide'
For rule 'cusdep glo gls cluster_guide', running '&do_cusdep( run_makeglossaries )' ...
Latexmk: Run number 2 of rule 'biber cluster_guide'
Latexmk: Run number 1 of rule 'cusdep acn acr cluster_guide'
For rule 'cusdep acn acr cluster_guide', running '&do_cusdep( run_makeglossaries )' ...
Latexmk: Run number 2 of rule 'pdflatex'
This is pdfTeX, Version 3.14159265-2.6-1.40.18 (MiKTeX 2.9.6500)
entering extended mode
This is makeindex, version 2.15 [MiKTeX 2.9.6500] (kpathsea + Thai support).
Scanning input file cluster_guide.idx....done (123 entries accepted, 0 rejected).
Sorting entries....done (955 comparisons).
Generating output file cluster_guide.ind....done (142 lines written, 0 warnings).
Output written in cluster_guide.ind.
Transcript written in cluster_guide.ilg.
Latexmk: Summary of warnings:
  Latex failed to resolve 9 reference(s)
Latexmk: Run number 2 of rule 'cusdep glo gls cluster_guide'
For rule 'cusdep glo gls cluster_guide', running '&do_cusdep( run_makeglossaries )' ...
Latexmk: Run number 2 of rule 'cusdep acn acr cluster_guide'
For rule 'cusdep acn acr cluster_guide', running '&do_cusdep( run_makeglossaries )' ...
Latexmk: Run number 3 of rule 'pdflatex'
This is pdfTeX, Version 3.14159265-2.6-1.40.18 (MiKTeX 2.9.6500)
entering extended mode
This is makeindex, version 2.15 [MiKTeX 2.9.6500] (kpathsea + Thai support).
Scanning input file cluster_guide.idx....done (123 entries accepted, 0 rejected).
Sorting entries....done (955 comparisons).
Generating output file cluster_guide.ind....done (142 lines written, 0 warnings).
Output written in cluster_guide.ind.
Transcript written in cluster_guide.ilg.
Latexmk: Summary of warnings:
  Latex failed to resolve 9 reference(s)
Latexmk: Run number 4 of rule 'pdflatex'
This is pdfTeX, Version 3.14159265-2.6-1.40.18 (MiKTeX 2.9.6500)
entering extended mode
This is makeindex, version 2.15 [MiKTeX 2.9.6500] (kpathsea + Thai support).
Scanning input file cluster_guide.idx....done (123 entries accepted, 0 rejected).
Sorting entries....done (955 comparisons).
Generating output file cluster_guide.ind....done (142 lines written, 0 warnings).
Output written in cluster_guide.ind.
Transcript written in cluster_guide.ilg.
Latexmk: Summary of warnings:
  Latex failed to resolve 9 reference(s)
```

**Comment by dpritchLibre** [comment]
That's good news that the document is at least compiling now.

However, it doesn't look as though it had to build a new `global_refs.bib`, or there would be some output for that at the very top.  So I'm still not able to tell if it worked or not.

From the `latex` directory, can you do:

    $ rm references/global_refs.bib
    $ make references/global_refs.bib

and see if this works?  Thanks

**Comment by BarkleyBG** [comment]
```
$ rm references/global_refs.bib

$ make references/global_refs.bib
/usr/bin/make -C references
make[1]: Entering directory `/cygdrive/c/Users/me..../LCC/latex/references'
./create_global_refs.sh 1_unix_and_linux.bib 2a_shell_intro.bib 2b_shell_programming.bib 3_computing_clusters.bib 4_running_r_scripts.bib 6_tips.bib
make[1]: execvp: ./create_global_refs.sh: Permission denied
make[1]: *** [global_refs.bib] Error 127
make[1]: Leaving directory `/cygdrive/c/Users/me.../LCC/latex/references'
make: *** [references/global_refs.bib] Error 2
```

**Comment by dpritchLibre** [comment]
Gah!!  I don't understand.

From the `latex/references` directory, does running the command `make` (i.e. no args) work?  Can we see the output of `ls -l` in `latex/references` again?  If we can't figure it out from this then I maybe we should shelve it until next time you visit and we can work on it in person.
